# Generated by Django 6.0.3 on 2026-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
