# Generated by Django 6.0.3 on 2026-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='banner_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
